// note- the pngs with fish1, fish2,... etc, are for higher difficulty levels because they look similar

export const fishList = [
    "anglerfish.png",
    "anglerfish2.png",
    "blackwhiteclownfish.png",
    "bluetang.png",
    "butterflyfish.png",
    "caesio.png",
    "chelmon.png",
    "clam.png",
    "clownfish.png",
    "fish1.png",
    "fish2.png",
    "fish3.png",
    "fish4.png",
    "fish5.png",
    "fish6.png",
    "fish7.png",
    "fish8.png",
    "fish9.png",
    "fish10.png",
    "fish11.png",
    "fish12.png",
    "flounder.png",
    "gardeneel.png",
    "jellyfish.png",
    "puffer.png",
    "seahorse.png",
    "seaturtle.png",
    "shrimp.png",
    "squid.png",
    "stingray.png",
    "triggerfish.png",
    "urchin.png",
    "whale.png",
    "whale2.png"
]